/* Form definition file generated by fdesign on Fri Apr 12 23:39:09 2019 */

#include <stdlib.h>
#include "main.h"


/***************************************
 ***************************************/

FD_main *
create_form_main( void )
{
    FL_OBJECT *obj;
    FD_main *fdui = ( FD_main * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->main = fl_bgn_form( FL_NO_BOX, 768, 1018 );

    fdui->all_container = obj = fl_add_box( FL_FLAT_BOX, 0, 0, 768, 1018, "" );
    fl_set_object_color( obj, FL_LEFT_BCOL, FL_COL1 );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, backlight_on, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 0, 0, 768, 1018, "" );
    fl_set_object_color( obj, FL_WHITE, FL_WHITE );
    fl_set_object_callback( obj, backlight_on, 0 );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 70, 610, 180, 310, "TV Power" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 490, 610, 180, 310, "TV Input" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    fdui->living_room_on = obj = fl_add_button( FL_NORMAL_BUTTON, 470, 50, 120, 120, "On" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, living_room_state, 2 );

    fdui->living_room_dim = obj = fl_add_button( FL_NORMAL_BUTTON, 320, 50, 120, 120, "Dim" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, living_room_state, 1 );

    fdui->living_room_off = obj = fl_add_button( FL_NORMAL_BUTTON, 170, 50, 120, 120, "Off" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, living_room_state, 0 );

    fdui->dining_room_on = obj = fl_add_button( FL_NORMAL_BUTTON, 260, 240, 230, 140, "Dining Room \nToggle" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, dining_room_state, 2 );

    fdui->stove_light_on = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 430, 150, 100, "Stove Light\nToggle" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, stove_state, 2 );

    fdui->tv_on = obj = fl_add_button( FL_NORMAL_BUTTON, 100, 630, 120, 120, "TV On" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, tv_on, 0 );

    fdui->tv_off = obj = fl_add_button( FL_NORMAL_BUTTON, 100, 770, 120, 120, "TV Off" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, tv_off, 0 );

    fdui->tv_chromecast = obj = fl_add_button( FL_NORMAL_BUTTON, 520, 630, 120, 120, "Cast" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, tv_chromecast, 0 );

    fdui->tv_switch = obj = fl_add_button( FL_NORMAL_BUTTON, 520, 770, 120, 120, "Switch" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, tv_switch, 0 );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 160, 20, 440, 180, "Living Room" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 588, 230, 180, 330, "Scenes" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );

    obj = fl_add_button( FL_NORMAL_BUTTON, 620, 260, 120, 120, "Night" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, scene_night, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 300, 580, 150, 100, "Kitchen\nToggle" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, kitchen_state, 2 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 738, 988, 30, 30, "exit" );
    fl_set_object_callback( obj, exit_button, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 620, 410, 120, 120, "Movies" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, scene_movies, 0 );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 0, 30, 110, 230, "Curtains" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT_TOP );

    obj = fl_add_button( FL_NORMAL_BUTTON, 10, 60, 80, 80, "Open" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, curtains_open, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 10, 160, 80, 80, "Close" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_callback( obj, curtains_close, 0 );

    obj = fl_add_labelframe( FL_ENGRAVED_FRAME, 260, 700, 220, 180, "RGB Strip" );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );

    obj = fl_add_button( FL_NORMAL_BUTTON, 270, 720, 50, 50, "R" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, rgbstrip_color, 1 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 420, 720, 50, 50, "B" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, rgbstrip_color, 3 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 340, 720, 50, 50, "G" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, rgbstrip_color, 2 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 270, 810, 50, 50, "W" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, rgbstrip_color, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 390, 810, 80, 50, "Off" );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_callback( obj, rgbstrip_off, 0 );

    fl_end_form( );

    fdui->main->fdui = fdui;

    return fdui;
}
