version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.8.2 # every job must define an image for the docker executor and subsequent jobs may define a different image.
    steps:
      - checkout
      - run:
          name: Prep cache
          command: sudo mkdir -p /venv; sudo chown -R circleci:circleci /venv;
      - run:
          name: Install deps
          command: sudo apt-get update && sudo apt-get install libudev-dev libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavutil-dev libpostproc-dev libswresample-dev libswscale-dev ffmpeg
      - restore_cache:
          key: hadep
      - run:
          name: Install pip dependencies
          command: |  # use pipenv to install dependencies
            python3.8 -m venv /venv
            source /venv/bin/activate
            pip3 install --pre --upgrade 'homeassistant==0.109.6'
      - save_cache:
          key: hadep
          paths:
            - "/venv"
      - run:
          name: HA Config Check
          command: |
            cd ~/project/ha-config
            cp secrets_redacted.yaml secrets.yaml
            source /venv/bin/activate
            hass -c . --script check_config --info all
      - save_cache:
          key: hadep
          paths:
            - "/venv"
