---
- name: Install and configure base iptables rules
  hosts: cluster
  become: yes
  tasks:
    - name: generate bird.conf
      template:
        src: 'iptables.rules.j2'
        dest: /etc/iptables/iptables.rules
      register: bird_conf
    - name: Ensure iptables rules are applied at boot time.
      service:
        name: iptables
        enabled: yes

