---
- name: All hosts up-to-date
  hosts: cluster
  become: yes
  vars:
    consulkey: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62646230323761636531656561653137653136346431396262623939316266323434376461303961
          3061666262613966333164366365386362346132646639630a313435353732353863393734366333
          37383534326534316563626162323336386165663537363966396532383561626461386564386165
          3236346364306132360a313132303965356332353634323732363534353563373134633163653164
          37303238656466376533666231326133353238626633373039613638383837653333616636316636
          3735663931386161343963613537663835353737636532356262
  vars_files:
    - consul/consul_secrets.yml
  tasks:
    - name: install consul
      pacman:
        update_cache: yes
        name:
          - consul
    - name: mkdir /etc/consul.d/certs
      file:
        owner: consul
        group: consul
        path: /etc/consul.d/certs
        state: directory
    - name: copy consul ca root cert
      copy:
        src: 'consul/consul-ca/consul-agent-ca.pem'
        dest: /etc/consul.d/certs/
        owner: consul
        group: consul
        mode: '664'
    - name: copy consul ca cert
      copy:
        src: 'consul/consul-ca/dc1-server-consul-{{ansible_hostname}}.pem'
        dest: /etc/consul.d/certs/
        owner: consul
        group: consul
        mode: '664'
    - name: copy consul ca key
      copy:
        src: 'consul/consul-ca/dc1-server-consul-{{ansible_hostname}}-key.pem'
        dest: /etc/consul.d/certs/
        owner: consul
        group: consul
        mode: '660'
    - name: generate consul.hcl
      template:
        src: 'consul/consul.hcl.j2'
        dest: /etc/consul.d/consul.hcl
      register: consul_conf
    - name: mkdir /etc/systemd/system/consul.service.d/
      file:
        owner: consul
        group: consul
        path: /etc/systemd/system/consul.service.d/
        state: directory
    - name: copy consul override file
      copy:
        src: 'consul/consul-override.conf'
        dest: /etc/systemd/system/consul.service.d/override.conf
    - name: systemctl daemon-reload
      command:
        cmd: 'systemctl daemon-reload'
    - name: mkdir /opt/consul
      file:
        owner: consul
        group: consul
        path: /opt/consul
        state: directory
    - name: Ensure consul is started and enabled
      service:
        name: consul
        state: started
        enabled: yes
    - name: Reload consul if consul.hcl has changed
      service:
        name: consul
        state: restarted
      when: consul_conf.changed
