---
- name: Vault secrets inserted into Nomad.
  hosts: cluster
  become: yes
  vars_files:
    - nomad/vault_secrets.yml
    - ../notsecret.yml
  tasks:
    - name: generate vault.hcl
      template:
        src: 'nomad/nomad-vault.hcl.j2'
        mode: "600"
        dest: /etc/nomad.d/vault.hcl
    - name: Restart nomad with vault token
      service:
        name: nomad
        state: restarted
