---
- name: Install and configure BIRD for anycast service on the cluster
  hosts: cloud
  become: yes
  vars_files:
    - wireguard/iplist.yml
  pre_tasks:
    - name: Gather facts from all cluster hosts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['cluster'] }}"
  tasks:
    - name: generate bird.conf
      template:
        src: 'bird/bird_cloud.conf.j2'
        dest: /etc/bird.conf
      register: bird_conf
    - name: Ensure bird is started and enabled
      service:
        name: bird
        state: started
        enabled: yes
    - name: Restart bird if defaults.hcl has changed
      service:
        name: bird
        state: restarted
      when: bird_conf.changed
