input_number:
    alarm_adam_hour:
        name: Hours
        icon: mdi:timer
        min: 0
        max: 23
        step: 1
    alarm_adam_minutes:
        name: Minutes
        icon: mdi:timer
        min: 0
        max: 59
        step: 1

input_boolean:
    alarm_adam_weekday:
        name: Weekdays
        icon: mdi:calendar
    alarm_adam_weekend:
        name: Weekends
        icon: mdi:calendar

sensor:
    - platform: template
      sensors:
         alarm_adam_time:
              friendly_name: 'Time'
              value_template: >-
                  {{ "%0.02d:%0.02d" | format(states("input_number.alarm_adam_hour") | int, states("input_number.alarm_adam_minutes") | int) }}

group:
    alarm_adam:
        name: Alarm Clock
        control: hidden
        entities:
            - sensor.alarm_adam_time
            - input_number.alarm_adam_hour
            - input_number.alarm_adam_minutes
            - input_boolean.alarm_adam_weekday
            - input_boolean.alarm_adam_weekend


automation:
    - id: alarm_adam_weekdays
      alias: "Wake me up (week) adam"
      trigger:
          - platform: time_pattern
            minutes: '/1'
            seconds: 0
      condition:
          - condition: state
            entity_id: input_boolean.alarm_adam_weekday
            state: 'on'
          - condition: time
            weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
          - condition: template
            value_template: >-
                {{ now().strftime("%H:%M") == states.sensor.alarm_adam_time.state }}
      action:
        service: scene.turn_on
        entity_id: scene.adams_room_full_slow

    - id: alarm_adam_weekend
      alias: "Wake me up (weekend) adam"
      trigger:
          - platform: time_pattern
            minutes: '/1'
            seconds: 0
      condition:
          - condition: state
            entity_id: input_boolean.alarm_adam_weekend
            state: 'on'
          - condition: time
            weekday:
                - sat
                - sun
          - condition: template
            value_template: >-
                {{ now().strftime("%H:%M") == states.sensor.alarm_adam_time.state }}
      action:
        service: scene.turn_on
        entity_id: scene.adams_room_full_slow
