input_number:
    alarm_alex_hour:
        name: Hours
        icon: mdi:timer
        min: 0
        max: 23
        step: 1
    alarm_alex_minutes:
        name: Minutes
        icon: mdi:timer
        min: 0
        max: 59
        step: 1

input_boolean:
    alarm_alex_weekday:
        name: Weekdays
        icon: mdi:calendar
    alarm_alex_weekend:
        name: Weekends
        icon: mdi:calendar

sensor:
    - platform: template
      sensors:
         alarm_alex_time:
              friendly_name: 'Time'
              value_template: >-
                  {{ "%0.02d:%0.02d" | format(states("input_number.alarm_alex_hour") | int, states("input_number.alarm_alex_minutes") | int) }}



automation:
    - id: alarm_alex_weekdays
      alias: "Wake me up (week) alex"
      trigger:
          - platform: time_pattern
            minutes: '/1'
            seconds: 0
      condition:
          - condition: state
            entity_id: input_boolean.alarm_alex_weekday
            state: 'on'
          - condition: time
            weekday:
                - mon
                - tue
                - wed
                - thu
                - fri
          - condition: template
            value_template: >-
                {{ now().strftime("%H:%M") == states.sensor.alarm_alex_time.state }}
      action:
        - service: scene.turn_on
          entity_id: scene.alexs_room_bulbone_slow
        - delay: '00:05:00'
        - service: scene.turn_on
          entity_id: scene.alexs_room_bulbtwo_slow
        - delay: '00:05:00'
        - service: scene.turn_on
          entity_id: scene.alexs_room_bedside_slow

    - id: alarm_alex_weekend
      alias: "Wake me up (weekend) alex"
      trigger:
          - platform: time_pattern
            minutes: '/1'
            seconds: 0
      condition:
          - condition: state
            entity_id: input_boolean.alarm_alex_weekend
            state: 'on'
          - condition: time
            weekday:
                - sat
                - sun
          - condition: template
            value_template: >-
                {{ now().strftime("%H:%M") == states.sensor.alarm_alex_time.state }}
      action:
        - service: scene.turn_on
          entity_id: scene.alexs_room_bulbone_slow
        - delay: '00:05:00'
        - service: scene.turn_on
          entity_id: scene.alexs_room_bulbtwo_slow
        - delay: '00:05:00'
        - service: scene.turn_on
          entity_id: scene.alexs_room_bedside_slow
