title: Home
views:
  - path: default_view
    title: default_view
    badges: []
    cards:
      - type: entities
        entities:
          - input_boolean.switch_shield
          - input_boolean.switch_alex_switch
        title: Alex TV Inputs
        show_header_toggle: false
      - type: entities
        entities:
          - light.living_room
          - light.kitchen_lights
          - light.kitchen
          - light.kitchen_cabinet_lights
          - switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch 
        title: Light
      - type: entities
        entities:
          - vacuum.roomba
        title: Roomba
      - type: thermostat
        entity: climate.home
      - type: glance
        entities:
          - sensor.home_temperature
          - sensor.home_humidity
      - type: entities
        entities:
          - sensor.last_door_open
          - sensor.door_lock
          - binary_sensor.entryway_motion
        title: Entryway
      - type: media-control
        entity: media_player.living_room_big_tv
    icon: 'mdi:home'
  - path: alarm
    title: Alarm
    badges: []
    cards:
      - type: alarm-panel
        name: 'Home Alarm'
        entity: alarm_control_panel.home_alarm
      - type: picture-entity
        entity: camera.door_camera
      - type: entities
        entities:
          - sensor.last_door_open
          - binary_sensor.entryway_motion
        title: 'Entryway Sensors'
  - path: office
    title: Office
    badges: []
    cards:
      - type: entities
        entities:
          - light.office
        title: Light
  - path: alexs_room
    title: Bedroom
    badges: []
    cards:
      - type: entities
        entities:
          - sensor.alarm_alex_time
          - input_number.alarm_alex_hour
          - input_number.alarm_alex_minutes
          - input_boolean.alarm_alex_weekday
          - input_boolean.alarm_alex_weekend
        title: Alarm Clock Test
        show_header_toggle: false
      - type: media-control
        entity: media_player.alex_tv
      - type: entities
        entities:
          - scene.as_room_bedside_only
          - scene.as_room_bright
          - scene.as_room_off
          - switch.leviton_dz15s_1bz_decora_smart_switch_switch
        title: Bedroom Scenes
        show_header_toggle: true
      - type: entities
        entities:
          - light.bedroom
        title: Light
  - path: automation
    title: Automation
    badges: []
    cards:
      - type: entities
        entities:
          - automation.adams_room_toggle
          - automation.alex_room_toggle
          - automation.alex_shield_input
          - automation.alex_switch_input
          - automation.dining_room_toggle
          - automation.fan_off_when_humidity_low_again
          - automation.fan_off_when_humidity_low_again_sarah
          - automation.fan_on_when_humidity_high
          - automation.fan_on_when_humidity_high_sarah
          - automation.living_room_night_mode
          - automation.make_a_coffee
          - automation.omers_room_toggle
          - automation.remote_light_strip_toggle
          - automation.sonoff_alex_light_toggle
          - automation.sonoff_tv_onoff
          - automation.sonoff_tv_shield
          - automation.sonoff_tv_switch
          - automation.tim_room_toggle
          - automation.wake_me_up_week_alex
          - automation.wake_me_up_weekend_alex
        title: all automations
        show_header_toggle: true
  - path: all_cameras
    title: Cameras
    badges: []
    cards:
      - type: picture-entity
        entity: camera.door_camera
      - type: picture-entity
        entity: camera.window_camera

